### PR TITLE
Update the code to use two spaces instead of tabs

### PR DESCRIPTION
**Pull request by r38y**
Hi there! I was looking through the code and poking things and noticed that you were using tabs everywhere. In the Ruby world everybody pretty much uses two spaces instead of tabs. This PR converts the app to that. I understand this may be a dickish PR, sorry :(.

### CODE REVIEW

**Comment by adafair** [comment]
Hah, I actually recently pushed to convert another ruby codebase over to tabs. I'm kind of curious why spaces would be preferred. I always thought that using tabs made more sense since 1 tab always represents 1 indentation level. From there, each person can adjust how indentation is rendered in their editors. When it's just spaces you have to know the right number of spaces for each file (2 from what I've seen before) and you're stuck with a smaller indentation visually if you prefer 4 spaces instead.

I'm all for sticking with whatever is standard I suppose. I just never really caught on as to why it was that way.

**Comment by adafair** [comment]
Thanks for looking over my code by the way :)

**Comment by r38y** [comment]
That is just the standard in the Ruby world. Yours is the first project
I've seen in a long time with tabs. You can set up your editor to use two
spaces when hitting tab if that is an issue. I don't think it is hard rule.
Just google for "ruby indentation" though.

Here is one example of a company codifying two spaces:
https://github.com/thoughtbot/guides/tree/master/style#formatting

If you personally prefer a larger indent, I wonder if editors would let you
change how it looks just for you?

> Thanks for looking over my code by the way :)

No problem :) I am working on something with Filepicker and it was great
seeing a project that has been updated recently.

On Mon, Aug 5, 2013 at 12:19 PM, adafair notifications@github.com wrote:

> Hah, I actually recently pushed to convert another ruby codebase over to
> tabs. I'm kind of curious why spaces would be preferred. I always thought
> that using tabs made more sense since 1 tab always represents 1 indentation
> level. From there, each person can adjust how indentation is rendered in
> their editors. When it's just spaces you have to know the right number of
> spaces for each file (2 from what I've seen before) and you're stuck with a
> smaller indentation visually if you prefer 4 spaces instead.
> 
> I'm all for sticking with whatever is standard I suppose. I just never
> really caught on as to why it was that way.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/infowrap/filepicker_client/pull/1#issuecomment-22117444
> .

## 

Randy Schmidt

**Comment by adafair** [comment]
Thanks

**Pull request merged**
